"use strict";
exports.__esModule = true;
exports.listModel = exports.todoModel = exports.userModel = void 0;
var client_1 = require("@prisma/client");
var userModel = require("./user");
exports.userModel = userModel;
var todoModel = require("./todo");
exports.todoModel = todoModel;
var listModel = require("./list");
exports.listModel = listModel;
var prisma = new client_1.PrismaClient();
exports["default"] = prisma;
